const redirects = async () => {
  const internetExplorerRedirect = {
    destination: '/ie-incompatible.html',
    has: [
      {
        type: 'header',
        key: 'user-agent',
        value: '(.*Trident.*)', // all ie browsers
      },
    ],
    permanent: false,
    source: '/:path((?!ie-incompatible.html$).*)', // all pages except the incompatibility page
  }

  // Service page slugs were changed to include a "-dubai-uae" location suffix
  // for SEO. These preserve existing rankings/backlinks to the old URLs.
  const serviceSlugRedirects = [
    { source: '/service/manual-retractable-monitor-solutions', destination: '/service/manual-retractable-monitor-solutions-dubai-uae', permanent: true },
    { source: '/service/video-conferencing-solutions', destination: '/service/video-conferencing-solutions-dubai-uae', permanent: true },
    { source: '/service/meeting-room-scheduling', destination: '/service/meeting-room-scheduling-dubai-uae', permanent: true },
    { source: '/service/anti-spoofing-and-impersonation-solution', destination: '/service/anti-spoofing-and-impersonation-solution-dubai-uae', permanent: true },
    { source: '/service/intelligent-threat-detection', destination: '/service/intelligent-threat-detection-dubai-uae', permanent: true },
    { source: '/service/soar-solution', destination: '/service/soar-solution-dubai-uae', permanent: true },
    { source: '/service/siem-solution', destination: '/service/siem-solution-dubai-uae', permanent: true },
    { source: '/service/sase-solution', destination: '/service/sase-solution-dubai-uae', permanent: true },
    { source: '/service/pam-pim-solutions', destination: '/service/pam-pim-solutions-dubai-uae', permanent: true },
    { source: '/service/mobile-device-management', destination: '/service/mobile-device-management-dubai-uae', permanent: true },
    { source: '/service/employee-monitoring', destination: '/service/employee-monitoring-dubai-uae', permanent: true },
    { source: '/service/web-application-firewall-waf', destination: '/service/web-application-firewall-waf-dubai-uae', permanent: true },
    { source: '/service/secure-email-smime', destination: '/service/secure-email-smime-dubai-uae', permanent: true },
    { source: '/service/managed-security-services', destination: '/service/managed-security-services-dubai-uae', permanent: true },
    { source: '/service/cloud-and-network-security', destination: '/service/cloud-and-network-security-dubai-uae', permanent: true },
    { source: '/service/vulnerability-assessment-and-penetration-testing', destination: '/service/vulnerability-assessment-and-penetration-testing-dubai-uae', permanent: true },
    { source: '/service/security-operations-center-soc', destination: '/service/security-operations-center-soc-dubai-uae', permanent: true },
    { source: '/service/cyber-security', destination: '/service/cyber-security-dubai-uae', permanent: true },
    { source: '/service/seo', destination: '/service/seo-dubai-uae', permanent: true },
    { source: '/service/server', destination: '/service/server-dubai-uae', permanent: true },
    { source: '/service/desktop-computers', destination: '/service/desktop-computers-dubai-uae', permanent: true },
    { source: '/service/business-laptops', destination: '/service/business-laptops-dubai-uae', permanent: true },
    { source: '/service/workstations', destination: '/service/workstations-dubai-uae', permanent: true },
    { source: '/service/printers', destination: '/service/printers-dubai-uae', permanent: true },
    { source: '/service/ups-systems', destination: '/service/ups-systems-dubai-uae', permanent: true },
    { source: '/service/routers', destination: '/service/routers-dubai-uae', permanent: true },
    { source: '/service/switches', destination: '/service/switches-dubai-uae', permanent: true },
    { source: '/service/firewalls', destination: '/service/firewalls-dubai-uae', permanent: true },
    { source: '/service/wireless-access-points', destination: '/service/wireless-access-points-dubai-uae', permanent: true },
    { source: '/service/network-cabinets', destination: '/service/network-cabinets-dubai-uae', permanent: true },
    { source: '/service/microsoft-licensing', destination: '/service/microsoft-licensing-dubai-uae', permanent: true },
    { source: '/service/adobe-licensing', destination: '/service/adobe-licensing-dubai-uae', permanent: true },
    { source: '/service/antivirus-licensing', destination: '/service/antivirus-licensing-dubai-uae', permanent: true },
    { source: '/service/windows-licensing', destination: '/service/windows-licensing-dubai-uae', permanent: true },
    { source: '/service/server-licensing', destination: '/service/server-licensing-dubai-uae', permanent: true },
    { source: '/service/hardware-and-software-services', destination: '/service/hardware-and-software-services-dubai-uae', permanent: true },
    { source: '/service/it-consulting', destination: '/service/it-consulting-dubai-uae', permanent: true },
    { source: '/service/digital-transformation', destination: '/service/digital-transformation-dubai-uae', permanent: true },
    { source: '/service/infrastructure-assessment', destination: '/service/infrastructure-assessment-dubai-uae', permanent: true },
    { source: '/service/cloud-readiness-assessment', destination: '/service/cloud-readiness-assessment-dubai-uae', permanent: true },
    { source: '/service/security-assessment', destination: '/service/security-assessment-dubai-uae', permanent: true },
    { source: '/service/site-survey', destination: '/service/site-survey-dubai-uae', permanent: true },
    { source: '/service/solution-design', destination: '/service/solution-design-dubai-uae', permanent: true },
    { source: '/service/installation', destination: '/service/installation-dubai-uae', permanent: true },
    { source: '/service/configuration', destination: '/service/configuration-dubai-uae', permanent: true },
    { source: '/service/migration', destination: '/service/migration-dubai-uae', permanent: true },
    { source: '/service/commissioning', destination: '/service/commissioning-dubai-uae', permanent: true },
    { source: '/service/user-training', destination: '/service/user-training-dubai-uae', permanent: true },
    { source: '/service/administrator-training', destination: '/service/administrator-training-dubai-uae', permanent: true },
    { source: '/service/documentation', destination: '/service/documentation-dubai-uae', permanent: true },
    { source: '/service/knowledge-transfer', destination: '/service/knowledge-transfer-dubai-uae', permanent: true },
    { source: '/service/professional-services', destination: '/service/professional-services-dubai-uae', permanent: true },
    { source: '/service/microsoft-365', destination: '/service/microsoft-365-dubai-uae', permanent: true },
    { source: '/service/microsoft-copilot', destination: '/service/microsoft-copilot-dubai-uae', permanent: true },
    { source: '/service/microsoft-sharepoint', destination: '/service/microsoft-sharepoint-dubai-uae', permanent: true },
    { source: '/service/security-consultation', destination: '/service/security-consultation-dubai-uae', permanent: true },
    { source: '/service/microsoft-365-migration', destination: '/service/microsoft-365-migration-dubai-uae', permanent: true },
    { source: '/service/microsoft-azure', destination: '/service/microsoft-azure-dubai-uae', permanent: true },
    { source: '/service/aws-cloud', destination: '/service/aws-cloud-dubai-uae', permanent: true },
    { source: '/service/cloud-migration', destination: '/service/cloud-migration-dubai-uae', permanent: true },
    { source: '/service/cloud-backup-solutions', destination: '/service/cloud-backup-solutions-dubai-uae', permanent: true },
    { source: '/service/disaster-recovery', destination: '/service/disaster-recovery-dubai-uae', permanent: true },
    { source: '/service/cloud-security', destination: '/service/cloud-security-dubai-uae', permanent: true },
    { source: '/service/google-cloud', destination: '/service/google-cloud-dubai-uae', permanent: true },
    { source: '/service/cloud-and-microsoft-solutions', destination: '/service/cloud-and-microsoft-solutions-dubai-uae', permanent: true },
    { source: '/service/ip-telephony', destination: '/service/ip-telephony-dubai-uae', permanent: true },
    { source: '/service/voip-solutions', destination: '/service/voip-solutions-dubai-uae', permanent: true },
    { source: '/service/cloud-pbx', destination: '/service/cloud-pbx-dubai-uae', permanent: true },
    { source: '/service/conference-phones', destination: '/service/conference-phones-dubai-uae', permanent: true },
    { source: '/service/call-center-solutions', destination: '/service/call-center-solutions-dubai-uae', permanent: true },
    { source: '/service/contact-center-solutions', destination: '/service/contact-center-solutions-dubai-uae', permanent: true },
    { source: '/service/call-recording-and-ivr', destination: '/service/call-recording-and-ivr-dubai-uae', permanent: true },
    { source: '/service/collaboration-displays', destination: '/service/collaboration-displays-dubai-uae', permanent: true },
    { source: '/service/unified-communication', destination: '/service/unified-communication-dubai-uae', permanent: true },
    { source: '/service/lan-and-wan', destination: '/service/lan-and-wan-dubai-uae', permanent: true },
    { source: '/service/vpn', destination: '/service/vpn-dubai-uae', permanent: true },
    { source: '/service/enterprise-wi-fi', destination: '/service/enterprise-wi-fi-dubai-uae', permanent: true },
    { source: '/service/network-optimization', destination: '/service/network-optimization-dubai-uae', permanent: true },
    { source: '/service/internet-load-balancing', destination: '/service/internet-load-balancing-dubai-uae', permanent: true },
    { source: '/service/cat6cat6a-cabling', destination: '/service/cat6cat6a-cabling-dubai-uae', permanent: true },
    { source: '/service/fiber-optic-cabling', destination: '/service/fiber-optic-cabling-dubai-uae', permanent: true },
    { source: '/service/network-rack-installation', destination: '/service/network-rack-installation-dubai-uae', permanent: true },
    { source: '/service/data-center-cabling', destination: '/service/data-center-cabling-dubai-uae', permanent: true },
    { source: '/service/network-monitoring', destination: '/service/network-monitoring-dubai-uae', permanent: true },
    { source: '/service/network-infrastructure', destination: '/service/network-infrastructure-dubai-uae', permanent: true },
    { source: '/service/server-installation', destination: '/service/server-installation-dubai-uae', permanent: true },
    { source: '/service/nas-storage', destination: '/service/nas-storage-dubai-uae', permanent: true },
    { source: '/service/san-storage', destination: '/service/san-storage-dubai-uae', permanent: true },
    { source: '/service/vmware', destination: '/service/vmware-dubai-uae', permanent: true },
    { source: '/service/hyper-v', destination: '/service/hyper-v-dubai-uae', permanent: true },
    { source: '/service/virtual-machines', destination: '/service/virtual-machines-dubai-uae', permanent: true },
    { source: '/service/server-rack-installation', destination: '/service/server-rack-installation-dubai-uae', permanent: true },
    { source: '/service/environmental-monitoring', destination: '/service/environmental-monitoring-dubai-uae', permanent: true },
    { source: '/service/cloud-backup', destination: '/service/cloud-backup-dubai-uae', permanent: true },
    { source: '/service/local-backup', destination: '/service/local-backup-dubai-uae', permanent: true },
    { source: '/service/hybrid-backup', destination: '/service/hybrid-backup-dubai-uae', permanent: true },
    { source: '/service/disaster-recovery-planning', destination: '/service/disaster-recovery-planning-dubai-uae', permanent: true },
    { source: '/service/data-recovery', destination: '/service/data-recovery-dubai-uae', permanent: true },
    { source: '/service/ransom-recovery', destination: '/service/ransom-recovery-dubai-uae', permanent: true },
    { source: '/service/business-continuity', destination: '/service/business-continuity-dubai-uae', permanent: true },
    { source: '/service/ai-cameras', destination: '/service/ai-cameras-dubai-uae', permanent: true },
    { source: '/service/access-control-and-bio-metric-attendance-system', destination: '/service/access-control-and-bio-metric-attendance-system-dubai-uae', permanent: true },
    { source: '/service/gate-barrier-and-automations', destination: '/service/gate-barrier-and-automations-dubai-uae', permanent: true },
    { source: '/service/intercom-systems', destination: '/service/intercom-systems-dubai-uae', permanent: true },
    { source: '/service/visitor-management-system', destination: '/service/visitor-management-system-dubai-uae', permanent: true },
    { source: '/service/anpr-systems', destination: '/service/anpr-systems-dubai-uae', permanent: true },
    { source: '/service/boardroom-solutions', destination: '/service/boardroom-solutions-dubai-uae', permanent: true },
    { source: '/service/meeting-room-solutions', destination: '/service/meeting-room-solutions-dubai-uae', permanent: true },
    { source: '/service/interactive-displays', destination: '/service/interactive-displays-dubai-uae', permanent: true },
    { source: '/service/digital-signage', destination: '/service/digital-signage-dubai-uae', permanent: true },
    { source: '/service/casting-solutions', destination: '/service/casting-solutions-dubai-uae', permanent: true },
    { source: '/service/smart-classroom-solutions', destination: '/service/smart-classroom-solutions-dubai-uae', permanent: true },
    { source: '/service/video-walls', destination: '/service/video-walls-dubai-uae', permanent: true },
    { source: '/service/cctv-installations', destination: '/service/cctv-installations-dubai-uae', permanent: true },
    { source: '/service/projectors', destination: '/service/projectors-dubai-uae', permanent: true },
    { source: '/service/public-addresspa-solutions', destination: '/service/public-addresspa-solutions-dubai-uae', permanent: true },
    { source: '/service/background-music', destination: '/service/background-music-dubai-uae', permanent: true },
    { source: '/service/auditorium-solutions', destination: '/service/auditorium-solutions-dubai-uae', permanent: true },
    { source: '/service/multi-room-audio', destination: '/service/multi-room-audio-dubai-uae', permanent: true },
    { source: '/service/speaker-system', destination: '/service/speaker-system-dubai-uae', permanent: true },
    { source: '/service/av-consultation', destination: '/service/av-consultation-dubai-uae', permanent: true },
    { source: '/service/av-programming', destination: '/service/av-programming-dubai-uae', permanent: true },
    { source: '/service/av-design-services', destination: '/service/av-design-services-dubai-uae', permanent: true },
    { source: '/service/smart-building-solutions', destination: '/service/smart-building-solutions-dubai-uae', permanent: true },
    { source: '/service/it-relocation', destination: '/service/it-relocation-dubai-uae', permanent: true },
    { source: '/service/it-asset-management', destination: '/service/it-asset-management-dubai-uae', permanent: true },
    { source: '/service/data-recovery-services', destination: '/service/data-recovery-services-dubai-uae', permanent: true },
    { source: '/service/desktop--endpoint-management', destination: '/service/desktop--endpoint-management-dubai-uae', permanent: true },
    { source: '/service/new-office-it-setup', destination: '/service/new-office-it-setup-dubai-uae', permanent: true },
    { source: '/service/remote-support', destination: '/service/remote-support-dubai-uae', permanent: true },
    { source: '/service/it-outsourcing', destination: '/service/it-outsourcing-dubai-uae', permanent: true },
    { source: '/service/on-call-it-support', destination: '/service/on-call-it-support-dubai-uae', permanent: true },
    { source: '/service/it-amc', destination: '/service/it-amc-dubai-uae', permanent: true },
    { source: '/service/data-loss-prevention-dlp', destination: '/service/data-loss-prevention-dlp-dubai-uae', permanent: true },
    { source: '/service/endpoint-security', destination: '/service/endpoint-security-dubai-uae', permanent: true },
    { source: '/service/email-security', destination: '/service/email-security-dubai-uae', permanent: true },
    { source: '/service/brand-identity-and-design', destination: '/service/brand-identity-and-design-dubai-uae', permanent: true },
    { source: '/service/ui-ux-design', destination: '/service/ui-ux-design-dubai-uae', permanent: true },
    { source: '/service/mobile-app-development', destination: '/service/mobile-app-development-dubai-uae', permanent: true },
    { source: '/service/web-development', destination: '/service/web-development-dubai-uae', permanent: true },
    { source: '/service/managed-it-service', destination: '/service/managed-it-service-dubai-uae', permanent: true },
    { source: '/service/it-infrastructure-service', destination: '/service/it-infrastructure-service-dubai-uae', permanent: true },
    { source: '/service/backup-and-business-continuity', destination: '/service/backup-and-business-continuity-dubai-uae', permanent: true },
    { source: '/service/security--surveillance-solutions', destination: '/service/security--surveillance-solutions-dubai-uae', permanent: true },
    { source: '/service/audio-visual-av-solutions', destination: '/service/audio-visual-av-solutions-dubai-uae', permanent: true },
  ]

  const redirects = [internetExplorerRedirect, ...serviceSlugRedirects]

  return redirects
}

export default redirects
